### PR TITLE
update Adding module desktop icons

### PR DESCRIPTION
**Pull request by FHenry**
update Adding module desktop icons according frappe v12 (don't know since when the actual documentation is not accurate)

### CODE REVIEW

**Comment by FHenry** [comment]
@revant As you review and merge my other PR on documentation https://github.com/frappe/frappe_docker/pull/376, could you please have a look to this one ?
There are on the forum some old or new threads about that. As the documentation is no more accurate, it can be time consuming for stressful for new developer. (As I've done myself, I spend some time to find how is works now ;-))

**Review by barredterra — CHANGES_REQUESTED** [review]
Hi @FHenry ,

This PR seems incomplete. Would you care to fix it?

In v12 there is a `$MY_APP/config/desktop.py` for desktop icons (top-level) and a file for each module (`$MY_APP/config/$MY_MODULE.py`). In v13 there are Workspaces, defined through the UI.

Please also [nicely format the code samples](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#code).

**Comment by FHenry** [comment]
I've update with a notice for v12. I didn't yet learn the v13 way

**Review by barredterra — CHANGES_REQUESTED** [review]
Please also [nicely format the code samples](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#code) and check your punctuation (full stop at the end of a sentence, etc.)

**Review by FHenry — COMMENTED** [review]
nice format python code done

**Comment by FHenry** [comment]
@barredterra done

**Comment by barredterra** [comment]
@FHenry I'd appreciate a little bit more effort on the next PR. It should not be the job of the reviewer to convert your quick notes into readable docs that can be published to hundreds or thousands of users.

**Comment by FHenry** [comment]
@barredterra ok, I'll take care with my next PR. thank to give me all these advice

**Pull request merged**
