### PR TITLE
fix(tutorial): Remove some outdated content

### PR DESCRIPTION
**Pull request by balamurali27**
Todo
- [x] Mention awesome bar instead of developer app
- [ ] Clarify web views

### CODE REVIEW

**Comment by iMoshi** [comment]
Hello, came here for a quick question. 

Installed the app to my Frappe instance and it's working beautifully. I like the theme and everything. However, can I manage the docs by hand using the backend of Frappe? Maybe inside the Website module..? 

Thank you, keep on rocking!

**Comment by balamurali27** [comment]
I don't get what you mean. Do you mean you installed frappe_docs?
Also, what do you mean you need to edit docs by hand?

For the record, I edit the markdown files to update docs..

**Comment by iMoshi** [comment]
I meant I've installed the app and I can navigate easily on the front end. But when I want to edit docs, add to it, I'd have to login to the server using a ftp client and edit the files. 

I would like to be able to synchronize the texts of the docs with my database, and when I want to edit the docs I'd like to edit using the backend of my Frappe install, but not by using ftp and opening it in Sublime text etc. 

Hope it's clear enough :)

**Comment by scmmishra** [comment]
Hey @iMoshi it's not possible as of now, you'll have to edit the markdown files directly, I'd suggest you to keep a local version in case you make changes often.

Otherwise, simply clone the repo and make changes directly for small updates or fixes

**Comment by iMoshi** [comment]
Gotcha. Thanks for the clarification :)

**Comment by balamurali27** [comment]
I forgot about this and lot of the changes have already been done.

**Pull request closed without merging**
