### PR TITLE
docs: auth hooks

### PR DESCRIPTION
**Pull request by revant**
hook for request authentication

Documentation for PR https://github.com/frappe/frappe/pull/12895

### CODE REVIEW

**Comment by barredterra** [comment]
Can you add an example / best practice how one would implement a custom auth method?

**Comment by revant** [comment]
There is no simple example.

I'll make custom app and share with community if PR gets merged.

I think flask, django allow to plug custom auth. It'll be similar to that.

What the custom app will do.

1. Check jwt from header
2. Verify signature of jwt (asymmetric)
3. If valid, check if the user from jwt exists and frappe.set_user()
4. If fail, do nothing. Let the request be guest request.

**Comment by gavindsouza** [comment]
@revant 

> I'll make custom app and share with community if PR gets merged.

That'd be super. Link it here as well when you do that!

> What the custom app will do.
>
> 1. Check jwt from header
> 2. Verify signature of jwt (asymmetric)
> 3. If valid, check if the user from jwt exists and frappe.set_user()
> 4. If fail, do nothing. Let the request be guest request.

Maybe you can add this in the docs here as well? Just the steps so that readers get a rough idea of how they could use this?

**Comment by revant** [comment]
https://github.com/castlecraft/castlecraft_auth

**Review by barredterra — APPROVED** [review]

**Pull request merged**
