### PR TITLE
Added an example for bench execute

### PR DESCRIPTION
**Pull request by TurkerTunali**
Added an example with parameters for bench execute command.

### CODE REVIEW

**Comment by gavindsouza** [comment]
@TurkerTunali Can you flesh out the existing section on [/docs/user/en/bench/frappe-commands](https://frappeframework.com/docs/user/en/bench/frappe-commands) and add a corresponding reference too similar to [/docs/user/en/bench/reference/drop-site](https://frappeframework.com/docs/user/en/bench/reference/drop-site)?

**Comment by gavindsouza** [comment]
@TurkerTunali Any Update?

**Comment by TurkerTunali** [comment]
Added https://github.com/frappe/frappe_docs/pull/171

**Comment by TurkerTunali** [comment]
> @TurkerTunali Any Update?

Added #171

**Comment by gavindsouza** [comment]
> > @TurkerTunali Any Update?
> 
> Added #171

Yeah, lets continue with that PR

**Pull request closed without merging**
