### PR TITLE
For API type, request should be made to "test_method"

### PR DESCRIPTION
**Pull request by TurkerTunali**
When I try to make a request to "api/method/test_method" we got an error in custom script because then it generates /server/api/method/api/method/test_method". 
It should be made to "test_method" in custom script. I am not sure about the custom apps.

### CODE REVIEW

**Comment by gavindsouza** [comment]
@TurkerTunali I'm not certain I understand what you're talking about here. Server scripts for API created under `test_method` will be accessible via `http://frappesite.com/api/method/test_method`; All standard Frappe API methods are prefixed with `/api/method/` conventionally.

**Comment by TurkerTunali** [comment]
When you try to reach the server sıde api within the Custom Script, you need to use the frappe.call ( "test_method") .

**Comment by gavindsouza** [comment]
@TurkerTunali That says more about how `frappe.call` handles Frappe API name conventions than the real name of the API. For instance, if you're using said API for external scripts or systems, you'll have to hit `/api/method/test_method` and not /test_method`. Perhaps you can add a note here saying that you could use `frappe.call("test_method")` instead?

**Comment by gavindsouza** [comment]
Are my changes acceptable to you? @TurkerTunali

**Comment by TurkerTunali** [comment]
> Are my changes acceptable to you? @TurkerTunali

Seems perfect.

**Comment by TurkerTunali** [comment]
Should I close this PR ?

**Review by gavindsouza — APPROVED** [review]

**Pull request merged**
