### PR TITLE
docs: Map view documentation

### PR DESCRIPTION
**Pull request by madmath03**
docs: Map view documentation for frappe/frappe#11202

Signed-off-by: mathieu.brunot <mathieu.brunot@monogramm.io>

### CODE REVIEW

**Comment by madmath03** [comment]
Just adding a comment to make sure it's not closed by any bot.

**Review by gavindsouza — CHANGES_REQUESTED** [review]
@madmath03 Can you re-do the gif to make it look consistent with the others on the same page? Having the same frame (that includes the navigation bar) would be a start. 

We would have to re-do all the screens with the new v13 UI sooner or later anyway. Perhaps you could use the [rebrand-ui](https://github.com/frappe/frappe/tree/rebrand-ui) branch to generate the gif?

**Comment by madmath03** [comment]
I'll see what I can do, but not promise on a deadline though...

**Comment by gavindsouza** [comment]
@madmath03 Any updates?

**Comment by madmath03** [comment]
@gavindsouza Not had the time yet, but I hope to be able to work on ERPNext 13 and this documentation next week 🤞

**Comment by gavindsouza** [comment]
Hey @madmath03, been a while since v13 is out. Can we get this page ready?

**Comment by madmath03** [comment]
It's currently not my priority, but I will try to do it as soon as I can...

**Comment by hasnain2808** [comment]
Hi @madmath03  ,

We moved to a new simpler contribution pipeline. Please move your changes in this PR to the new site when you're ready.

You can now directly contribute to frappeframework.com. For new contribution guidelines, refer to frappeframework.com/contribute.

Thanks for the contribution!

**Pull request closed without merging**
